### ISSUE TITLE
Recommend a linter for Lisp?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xlisp#6]
This may or may not be appropriate in this language. See exercism/docs#54 for details.

**Comment by kytrinyx** [comment]
Kind of random question--have you heard of lisp critic? Someone I know is pretty excited about it.

**Comment by wobh** [comment]
This "Lisp Critic" http://cs.northwestern.edu/academics/courses/325/exercises/critic.php ?

Pluses: it's by Chris Riesbeck whose Lisp-Unit tests we already use and whose class syllabus we recommend in our documentation, which is full of great stuff.

Minuses: None immediately evident.

We'll have to try it out. A quick scan of it's source code http://cs.northwestern.edu/academics/courses/325/programs/cs325/lisp-critic.lisp suggests there are a few known limitations, so it might be that SBCL's style warnings are sufficient or perhaps even better, while it might still be useful for someone using another implementation. We could perhaps add links to any or all of these resources

- Peter Norvig and Kent Pitman's Tutorial on Good Lisp Programming Style: http://norvig.com/luv-slides.ps PDF here: http://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf
- Google's CL style guide: http://google-styleguide.googlecode.com/svn/trunk/lispguide.xml
- Chris Riesbeck's style guide (likely the origin of lisp critic): http://cs.northwestern.edu/academics/courses/325/readings/lisp-style.php but also:
 - Riesbeck on Naming: http://cs.northwestern.edu/academics/courses/325/readings/names.php
 - Riesbeck's Cardinal Rule of Functions: http://cs.northwestern.edu/academics/courses/325/readings/cardinal-rule.php
  - Riesbeck's notes on things one should not imitate about Paul's Graham's code in _ANSI Common Lisp_ (otherwise used as the text book) http://cs.northwestern.edu/academics/courses/325/readings/graham/graham-notes.php

Not quite on style but emergently useful working with this topic:

- Peter Norvig's retrospective on his classic _Paradigms of AI Programming_, especially the section on "What Lessons are in PAIP?"  http://www.norvig.com/Lisp-retro.html
- Peter Norvig's Design Patterns in Dynamic Programming http://norvig.com/design-patterns/design-patterns.pdf
- Jeff Dalton's Common Lisp Pitfalls: http://www.aiai.ed.ac.uk/~jeff/lisp/cl-pitfalls

**Comment by kytrinyx** [comment]
Yeah, the Chris Riesbeck one.

I just followed some of your links. I love this:

> Bad names reduce code maintainability. Names are bad when they are:
> - cryptic, e.g., bltx
> - hopelessly vague, e.g., data
> - overly verbose, e.g., first-item-to-delete
> - misleading, e.g., num for something that holds a list of numbers
> Good names are:
> - short
> - plain English or follow common convention
> - accurate

Anyway, yeah, I think that it could be useful to link to these things.

**Comment by verdammelt** [comment]
@wobh These look like good resources. Lisp Critic seems to be a function which you pass a symbol bound to a function. If we wanted to we could probably build that in to the test files - but only for the exported functions. Now that I type that I doubt that it would be useful (unless it descends to functions called by the function provided).

@kytrinyx your formatting caused the "good" items to flow in with the "bad" items - scanning it this morning before coffee I was very confused by 'short' & 'accurate' where signs of bad names! :)

 I've been "away" from this track for a while but am trying to come back; these links could go in the SETUP.md file that all the tracks are going to have.

**Comment by kytrinyx** [comment]
d'oh! Fixed :)
